### ISSUE TITLE
Especificação do Projeto - Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by clarenceaguiar** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2024-1-e2-proj-int-t2-cabide-solidario#17]
Fazer um modelo gráfico e uma tabela com as descrições sucintas dos casos de uso e dos atores.

**Comment by AbVini** [comment]
https://lucid.app/lucidchart/e34a6eb7-07d8-4c11-ae1a-0f1d99ed330f/edit?viewport_loc=-1689%2C-748%2C6059%2C2785%2C.Q4MUjXso07N&invitationId=inv_b6dc0194-f930-451d-91b0-5cd361166133
